services:
#  sighas-be-app:
#    build: .
#    ports:
#      - "8080:8080"
#    depends_on:
#      - database
#    networks:
#      - sighas-be-network

  database:
    image: postgres:latest
    container_name: sighas-database
    restart: always
    environment:
      - POSTGRES_DB=sighas
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    networks:
      - sighas-be-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@pgadmin.org"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "8081:80"
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin

networks:
  sighas-be-network:
    driver: bridge