services:
  database:
    image: postgres:latest
    container_name: sighas-database
    restart: always
    environment:
      - POSTGRES_DB=sighas
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    networks:
      - sighas-be-network

  app:
    build: .
    container_name: sighas-be
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - DATABASE_URL=jdbc:postgresql://sighas-database:5432/sighas
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=admin
    networks:
      - sighas-be-network

#  pgadmin:
#    image: dpage/pgadmin4:latest
#    container_name: pgadmin
#    restart: always
#    environment:
#      PGADMIN_DEFAULT_EMAIL: "admin@pgadmin.org"
#      PGADMIN_DEFAULT_PASSWORD: "admin"
#    ports:
#      - "8081:80"

networks:
  sighas-be-network:
    driver: bridge
