services:
  database:
    image: postgres:latest
    container_name: sighas-database
    restart: always
    environment:
      - POSTGRES_DB=sighas
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
