--
-- PostgreSQL database dump
--

-- Dumped from database version 16.4 (Debian 16.4-1.pgdg120+1)
-- Dumped by pg_dump version 16.4

-- Started on 2024-12-05 19:39:18 UTC

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 3612 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 215 (class 1259 OID 24234)
-- Name: group_id; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.group_id (
    group_id uuid,
    id uuid NOT NULL
);


ALTER TABLE public.group_id OWNER TO admin;

--
-- TOC entry 216 (class 1259 OID 24239)
-- Name: tab_administrative_public_servant; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tab_administrative_public_servant (
    id uuid NOT NULL
);


ALTER TABLE public.tab_administrative_public_servant OWNER TO admin;

--
-- TOC entry 217 (class 1259 OID 24244)
-- Name: tab_affiliation; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tab_affiliation (
    ending_date date,
    starting_date date NOT NULL,
    status smallint NOT NULL,
    id uuid NOT NULL,
    user_id uuid,
    CONSTRAINT tab_affiliation_status_check CHECK (((status >= 0) AND (status <= 3)))
);


ALTER TABLE public.tab_affiliation OWNER TO admin;

--
-- TOC entry 219 (class 1259 OID 24251)
-- Name: tab_building; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tab_building (
    type smallint,
    id bigint NOT NULL,
    code character varying(255),
    CONSTRAINT tab_building_type_check CHECK (((type >= 0) AND (type <= 4)))
);


ALTER TABLE public.tab_building OWNER TO admin;

--
-- TOC entry 218 (class 1259 OID 24250)
-- Name: tab_building_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.tab_building ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tab_building_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 24257)
-- Name: tab_classroom; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tab_classroom (
    status smallint,
    id uuid NOT NULL,
    code character varying(255),
    CONSTRAINT tab_classroom_status_check CHECK (((status >= 0) AND (status <= 3)))
);


ALTER TABLE public.tab_classroom OWNER TO admin;

--
-- TOC entry 221 (class 1259 OID 24263)
-- Name: tab_computer_laboratory; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tab_computer_laboratory (
    status smallint,
    id uuid NOT NULL,
    code character varying(255),
    CONSTRAINT tab_computer_laboratory_status_check CHECK (((status >= 0) AND (status <= 3)))
);


ALTER TABLE public.tab_computer_laboratory OWNER TO admin;

--
-- TOC entry 222 (class 1259 OID 24269)
-- Name: tab_course; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tab_course (
    quantity_of_semesters integer,
    id uuid NOT NULL,
    code character varying(255),
    short_title character varying(255),
    title character varying(255)
);


ALTER TABLE public.tab_course OWNER TO admin;

--
-- TOC entry 223 (class 1259 OID 24276)
-- Name: tab_course_calendar; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tab_course_calendar (
    id uuid NOT NULL,
    title character varying(255)
);


ALTER TABLE public.tab_course_calendar OWNER TO admin;

--
-- TOC entry 224 (class 1259 OID 24281)
-- Name: tab_course_has_subject; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tab_course_has_subject (
    course_id uuid NOT NULL,
    subjects_id uuid NOT NULL
);


ALTER TABLE public.tab_course_has_subject OWNER TO admin;

--
-- TOC entry 225 (class 1259 OID 24286)
-- Name: tab_department; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tab_department (
    id uuid NOT NULL,
    code character varying(255) NOT NULL,
    title character varying(255) NOT NULL
);


ALTER TABLE public.tab_department OWNER TO admin;

--
-- TOC entry 226 (class 1259 OID 24295)
-- Name: tab_group; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tab_group (
    status smallint,
    id uuid NOT NULL,
    subject_id uuid,
    code character varying(255),
    CONSTRAINT tab_group_status_check CHECK (((status >= 0) AND (status <= 2)))
);


ALTER TABLE public.tab_group OWNER TO admin;

--
-- TOC entry 227 (class 1259 OID 24301)
-- Name: tab_group_has_professor; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tab_group_has_professor (
    group_id uuid NOT NULL,
    professors_id uuid NOT NULL
);


ALTER TABLE public.tab_group_has_professor OWNER TO admin;

--
-- TOC entry 228 (class 1259 OID 24306)
-- Name: tab_group_has_student; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tab_group_has_student (
    group_id uuid NOT NULL,
    students_id uuid NOT NULL
);


ALTER TABLE public.tab_group_has_student OWNER TO admin;

--
-- TOC entry 229 (class 1259 OID 24311)
-- Name: tab_internal_room; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tab_internal_room (
    building_id bigint,
    id uuid NOT NULL,
    observations character varying(255)
);


ALTER TABLE public.tab_internal_room OWNER TO admin;

--
-- TOC entry 230 (class 1259 OID 24316)
-- Name: tab_lesson_reservation; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tab_lesson_reservation (
    day smallint,
    ending_time time(6) without time zone,
    starting_time time(6) without time zone,
    classroom_id uuid,
    id uuid NOT NULL,
    CONSTRAINT tab_lesson_reservation_day_check CHECK (((day >= 0) AND (day <= 6)))
);


ALTER TABLE public.tab_lesson_reservation OWNER TO admin;

--
-- TOC entry 231 (class 1259 OID 24322)
-- Name: tab_professor; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tab_professor (
    id uuid NOT NULL,
    institutional_email character varying(255) NOT NULL
);


ALTER TABLE public.tab_professor OWNER TO admin;

--
-- TOC entry 232 (class 1259 OID 24329)
-- Name: tab_professor_calendar; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tab_professor_calendar (
    id uuid NOT NULL,
    title character varying(255)
);


ALTER TABLE public.tab_professor_calendar OWNER TO admin;

--
-- TOC entry 233 (class 1259 OID 24334)
-- Name: tab_professor_groups; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tab_professor_groups (
    groups_id uuid NOT NULL,
    professor_id uuid NOT NULL
);


ALTER TABLE public.tab_professor_groups OWNER TO admin;

--
-- TOC entry 234 (class 1259 OID 24339)
-- Name: tab_public_servant; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tab_public_servant (
    education_level smallint NOT NULL,
    dapartment_id uuid,
    id uuid NOT NULL,
    siape character varying(255) NOT NULL,
    CONSTRAINT tab_public_servant_education_level_check CHECK (((education_level >= 0) AND (education_level <= 8)))
);


ALTER TABLE public.tab_public_servant OWNER TO admin;

--
-- TOC entry 235 (class 1259 OID 24347)
-- Name: tab_public_servant_has_role; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tab_public_servant_has_role (
    public_servant_role_id bigint NOT NULL,
    public_servant_id uuid NOT NULL
);


ALTER TABLE public.tab_public_servant_has_role OWNER TO admin;

--
-- TOC entry 237 (class 1259 OID 24353)
-- Name: tab_public_servant_role; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tab_public_servant_role (
    id bigint NOT NULL,
    role character varying(255) NOT NULL,
    CONSTRAINT tab_public_servant_role_role_check CHECK (((role)::text = 'COURSE_COORDINATOR'::text))
);


ALTER TABLE public.tab_public_servant_role OWNER TO admin;

--
-- TOC entry 236 (class 1259 OID 24352)
-- Name: tab_public_servant_role_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.tab_public_servant_role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tab_public_servant_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 238 (class 1259 OID 24361)
-- Name: tab_student; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tab_student (
    course_id uuid,
    id uuid NOT NULL,
    enrollment character varying(255) NOT NULL,
    institutional_email character varying(255) NOT NULL
);


ALTER TABLE public.tab_student OWNER TO admin;

--
-- TOC entry 239 (class 1259 OID 24372)
-- Name: tab_student_calendar; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tab_student_calendar (
    id uuid NOT NULL,
    title character varying(255)
);


ALTER TABLE public.tab_student_calendar OWNER TO admin;

--
-- TOC entry 240 (class 1259 OID 24377)
-- Name: tab_student_groups; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tab_student_groups (
    groups_id uuid NOT NULL,
    student_id uuid NOT NULL
);


ALTER TABLE public.tab_student_groups OWNER TO admin;

--
-- TOC entry 241 (class 1259 OID 24382)
-- Name: tab_subject; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tab_subject (
    id uuid NOT NULL,
    code character varying(255),
    short_tile character varying(255),
    title character varying(255)
);


ALTER TABLE public.tab_subject OWNER TO admin;

--
-- TOC entry 242 (class 1259 OID 24389)
-- Name: tab_subject_courses; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tab_subject_courses (
    courses_id uuid NOT NULL,
    subject_id uuid NOT NULL
);


ALTER TABLE public.tab_subject_courses OWNER TO admin;

--
-- TOC entry 243 (class 1259 OID 24394)
-- Name: tab_user; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tab_user (
    birthdate date NOT NULL,
    id uuid NOT NULL,
    password character varying(100) NOT NULL,
    cpf character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    surname character varying(255) NOT NULL,
    username character varying(255) NOT NULL
);


ALTER TABLE public.tab_user OWNER TO admin;

--
-- TOC entry 244 (class 1259 OID 24407)
-- Name: tab_user_has_role; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tab_user_has_role (
    user_role_id integer NOT NULL,
    user_id uuid NOT NULL
);


ALTER TABLE public.tab_user_has_role OWNER TO admin;

--
-- TOC entry 245 (class 1259 OID 24412)
-- Name: tab_user_role; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tab_user_role (
    id integer NOT NULL,
    role character varying(255) NOT NULL,
    CONSTRAINT tab_user_role_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'USER'::character varying])::text[])))
);


ALTER TABLE public.tab_user_role OWNER TO admin;

--
-- TOC entry 3576 (class 0 OID 24234)
-- Dependencies: 215
-- Data for Name: group_id; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.group_id (group_id, id) FROM stdin;
\.


--
-- TOC entry 3577 (class 0 OID 24239)
-- Dependencies: 216
-- Data for Name: tab_administrative_public_servant; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.tab_administrative_public_servant (id) FROM stdin;
\.


--
-- TOC entry 3578 (class 0 OID 24244)
-- Dependencies: 217
-- Data for Name: tab_affiliation; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.tab_affiliation (ending_date, starting_date, status, id, user_id) FROM stdin;
\.


--
-- TOC entry 3580 (class 0 OID 24251)
-- Dependencies: 219
-- Data for Name: tab_building; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.tab_building (type, id, code) FROM stdin;
\.


--
-- TOC entry 3581 (class 0 OID 24257)
-- Dependencies: 220
-- Data for Name: tab_classroom; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.tab_classroom (status, id, code) FROM stdin;
\.


--
-- TOC entry 3582 (class 0 OID 24263)
-- Dependencies: 221
-- Data for Name: tab_computer_laboratory; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.tab_computer_laboratory (status, id, code) FROM stdin;
\.


--
-- TOC entry 3583 (class 0 OID 24269)
-- Dependencies: 222
-- Data for Name: tab_course; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.tab_course (quantity_of_semesters, id, code, short_title, title) FROM stdin;
\.


--
-- TOC entry 3584 (class 0 OID 24276)
-- Dependencies: 223
-- Data for Name: tab_course_calendar; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.tab_course_calendar (id, title) FROM stdin;
\.


--
-- TOC entry 3585 (class 0 OID 24281)
-- Dependencies: 224
-- Data for Name: tab_course_has_subject; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.tab_course_has_subject (course_id, subjects_id) FROM stdin;
\.


--
-- TOC entry 3586 (class 0 OID 24286)
-- Dependencies: 225
-- Data for Name: tab_department; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.tab_department (id, code, title) FROM stdin;
\.


--
-- TOC entry 3587 (class 0 OID 24295)
-- Dependencies: 226
-- Data for Name: tab_group; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.tab_group (status, id, subject_id, code) FROM stdin;
\.


--
-- TOC entry 3588 (class 0 OID 24301)
-- Dependencies: 227
-- Data for Name: tab_group_has_professor; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.tab_group_has_professor (group_id, professors_id) FROM stdin;
\.


--
-- TOC entry 3589 (class 0 OID 24306)
-- Dependencies: 228
-- Data for Name: tab_group_has_student; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.tab_group_has_student (group_id, students_id) FROM stdin;
\.


--
-- TOC entry 3590 (class 0 OID 24311)
-- Dependencies: 229
-- Data for Name: tab_internal_room; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.tab_internal_room (building_id, id, observations) FROM stdin;
\.


--
-- TOC entry 3591 (class 0 OID 24316)
-- Dependencies: 230
-- Data for Name: tab_lesson_reservation; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.tab_lesson_reservation (day, ending_time, starting_time, classroom_id, id) FROM stdin;
\.


--
-- TOC entry 3592 (class 0 OID 24322)
-- Dependencies: 231
-- Data for Name: tab_professor; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.tab_professor (id, institutional_email) FROM stdin;
\.


--
-- TOC entry 3593 (class 0 OID 24329)
-- Dependencies: 232
-- Data for Name: tab_professor_calendar; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.tab_professor_calendar (id, title) FROM stdin;
\.


--
-- TOC entry 3594 (class 0 OID 24334)
-- Dependencies: 233
-- Data for Name: tab_professor_groups; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.tab_professor_groups (groups_id, professor_id) FROM stdin;
\.


--
-- TOC entry 3595 (class 0 OID 24339)
-- Dependencies: 234
-- Data for Name: tab_public_servant; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.tab_public_servant (education_level, dapartment_id, id, siape) FROM stdin;
\.


--
-- TOC entry 3596 (class 0 OID 24347)
-- Dependencies: 235
-- Data for Name: tab_public_servant_has_role; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.tab_public_servant_has_role (public_servant_role_id, public_servant_id) FROM stdin;
\.


--
-- TOC entry 3598 (class 0 OID 24353)
-- Dependencies: 237
-- Data for Name: tab_public_servant_role; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.tab_public_servant_role (id, role) FROM stdin;
\.


--
-- TOC entry 3599 (class 0 OID 24361)
-- Dependencies: 238
-- Data for Name: tab_student; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.tab_student (course_id, id, enrollment, institutional_email) FROM stdin;
\.


--
-- TOC entry 3600 (class 0 OID 24372)
-- Dependencies: 239
-- Data for Name: tab_student_calendar; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.tab_student_calendar (id, title) FROM stdin;
\.


--
-- TOC entry 3601 (class 0 OID 24377)
-- Dependencies: 240
-- Data for Name: tab_student_groups; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.tab_student_groups (groups_id, student_id) FROM stdin;
\.


--
-- TOC entry 3602 (class 0 OID 24382)
-- Dependencies: 241
-- Data for Name: tab_subject; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.tab_subject (id, code, short_tile, title) FROM stdin;
\.


--
-- TOC entry 3603 (class 0 OID 24389)
-- Dependencies: 242
-- Data for Name: tab_subject_courses; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.tab_subject_courses (courses_id, subject_id) FROM stdin;
\.


--
-- TOC entry 3604 (class 0 OID 24394)
-- Dependencies: 243
-- Data for Name: tab_user; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.tab_user (birthdate, id, password, cpf, email, name, surname, username) FROM stdin;
\.


--
-- TOC entry 3605 (class 0 OID 24407)
-- Dependencies: 244
-- Data for Name: tab_user_has_role; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.tab_user_has_role (user_role_id, user_id) FROM stdin;
\.


--
-- TOC entry 3606 (class 0 OID 24412)
-- Dependencies: 245
-- Data for Name: tab_user_role; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.tab_user_role (id, role) FROM stdin;
\.


--
-- TOC entry 3613 (class 0 OID 0)
-- Dependencies: 218
-- Name: tab_building_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.tab_building_id_seq', 1, false);


--
-- TOC entry 3614 (class 0 OID 0)
-- Dependencies: 236
-- Name: tab_public_servant_role_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.tab_public_servant_role_id_seq', 1, false);


--
-- TOC entry 3326 (class 2606 OID 24238)
-- Name: group_id group_id_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.group_id
    ADD CONSTRAINT group_id_pkey PRIMARY KEY (id);


--
-- TOC entry 3328 (class 2606 OID 24243)
-- Name: tab_administrative_public_servant tab_administrative_public_servant_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_administrative_public_servant
    ADD CONSTRAINT tab_administrative_public_servant_pkey PRIMARY KEY (id);


--
-- TOC entry 3330 (class 2606 OID 24249)
-- Name: tab_affiliation tab_affiliation_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_affiliation
    ADD CONSTRAINT tab_affiliation_pkey PRIMARY KEY (id);


--
-- TOC entry 3332 (class 2606 OID 24256)
-- Name: tab_building tab_building_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_building
    ADD CONSTRAINT tab_building_pkey PRIMARY KEY (id);


--
-- TOC entry 3334 (class 2606 OID 24262)
-- Name: tab_classroom tab_classroom_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_classroom
    ADD CONSTRAINT tab_classroom_pkey PRIMARY KEY (id);


--
-- TOC entry 3336 (class 2606 OID 24268)
-- Name: tab_computer_laboratory tab_computer_laboratory_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_computer_laboratory
    ADD CONSTRAINT tab_computer_laboratory_pkey PRIMARY KEY (id);


--
-- TOC entry 3340 (class 2606 OID 24280)
-- Name: tab_course_calendar tab_course_calendar_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_course_calendar
    ADD CONSTRAINT tab_course_calendar_pkey PRIMARY KEY (id);


--
-- TOC entry 3342 (class 2606 OID 24285)
-- Name: tab_course_has_subject tab_course_has_subject_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_course_has_subject
    ADD CONSTRAINT tab_course_has_subject_pkey PRIMARY KEY (course_id, subjects_id);


--
-- TOC entry 3338 (class 2606 OID 24275)
-- Name: tab_course tab_course_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_course
    ADD CONSTRAINT tab_course_pkey PRIMARY KEY (id);


--
-- TOC entry 3344 (class 2606 OID 24292)
-- Name: tab_department tab_department_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_department
    ADD CONSTRAINT tab_department_pkey PRIMARY KEY (id);


--
-- TOC entry 3350 (class 2606 OID 24305)
-- Name: tab_group_has_professor tab_group_has_professor_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_group_has_professor
    ADD CONSTRAINT tab_group_has_professor_pkey PRIMARY KEY (group_id, professors_id);


--
-- TOC entry 3352 (class 2606 OID 24310)
-- Name: tab_group_has_student tab_group_has_student_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_group_has_student
    ADD CONSTRAINT tab_group_has_student_pkey PRIMARY KEY (group_id, students_id);


--
-- TOC entry 3348 (class 2606 OID 24300)
-- Name: tab_group tab_group_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_group
    ADD CONSTRAINT tab_group_pkey PRIMARY KEY (id);


--
-- TOC entry 3354 (class 2606 OID 24315)
-- Name: tab_internal_room tab_internal_room_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_internal_room
    ADD CONSTRAINT tab_internal_room_pkey PRIMARY KEY (id);


--
-- TOC entry 3356 (class 2606 OID 24321)
-- Name: tab_lesson_reservation tab_lesson_reservation_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_lesson_reservation
    ADD CONSTRAINT tab_lesson_reservation_pkey PRIMARY KEY (id);


--
-- TOC entry 3362 (class 2606 OID 24333)
-- Name: tab_professor_calendar tab_professor_calendar_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_professor_calendar
    ADD CONSTRAINT tab_professor_calendar_pkey PRIMARY KEY (id);


--
-- TOC entry 3364 (class 2606 OID 24338)
-- Name: tab_professor_groups tab_professor_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_professor_groups
    ADD CONSTRAINT tab_professor_groups_pkey PRIMARY KEY (groups_id, professor_id);


--
-- TOC entry 3358 (class 2606 OID 24326)
-- Name: tab_professor tab_professor_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_professor
    ADD CONSTRAINT tab_professor_pkey PRIMARY KEY (id);


--
-- TOC entry 3370 (class 2606 OID 24351)
-- Name: tab_public_servant_has_role tab_public_servant_has_role_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_public_servant_has_role
    ADD CONSTRAINT tab_public_servant_has_role_pkey PRIMARY KEY (public_servant_role_id, public_servant_id);


--
-- TOC entry 3366 (class 2606 OID 24344)
-- Name: tab_public_servant tab_public_servant_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_public_servant
    ADD CONSTRAINT tab_public_servant_pkey PRIMARY KEY (id);


--
-- TOC entry 3372 (class 2606 OID 24358)
-- Name: tab_public_servant_role tab_public_servant_role_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_public_servant_role
    ADD CONSTRAINT tab_public_servant_role_pkey PRIMARY KEY (id);


--
-- TOC entry 3382 (class 2606 OID 24376)
-- Name: tab_student_calendar tab_student_calendar_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_student_calendar
    ADD CONSTRAINT tab_student_calendar_pkey PRIMARY KEY (id);


--
-- TOC entry 3384 (class 2606 OID 24381)
-- Name: tab_student_groups tab_student_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_student_groups
    ADD CONSTRAINT tab_student_groups_pkey PRIMARY KEY (groups_id, student_id);


--
-- TOC entry 3376 (class 2606 OID 24367)
-- Name: tab_student tab_student_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_student
    ADD CONSTRAINT tab_student_pkey PRIMARY KEY (id);


--
-- TOC entry 3388 (class 2606 OID 24393)
-- Name: tab_subject_courses tab_subject_courses_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_subject_courses
    ADD CONSTRAINT tab_subject_courses_pkey PRIMARY KEY (courses_id, subject_id);


--
-- TOC entry 3386 (class 2606 OID 24388)
-- Name: tab_subject tab_subject_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_subject
    ADD CONSTRAINT tab_subject_pkey PRIMARY KEY (id);


--
-- TOC entry 3398 (class 2606 OID 24411)
-- Name: tab_user_has_role tab_user_has_role_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_user_has_role
    ADD CONSTRAINT tab_user_has_role_pkey PRIMARY KEY (user_role_id, user_id);


--
-- TOC entry 3390 (class 2606 OID 24400)
-- Name: tab_user tab_user_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_user
    ADD CONSTRAINT tab_user_pkey PRIMARY KEY (id);


--
-- TOC entry 3400 (class 2606 OID 24417)
-- Name: tab_user_role tab_user_role_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_user_role
    ADD CONSTRAINT tab_user_role_pkey PRIMARY KEY (id);


--
-- TOC entry 3346 (class 2606 OID 24294)
-- Name: tab_department un_code_tab_department; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_department
    ADD CONSTRAINT un_code_tab_department UNIQUE (code);


--
-- TOC entry 3392 (class 2606 OID 24402)
-- Name: tab_user un_cpf_tab_user; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_user
    ADD CONSTRAINT un_cpf_tab_user UNIQUE (cpf);


--
-- TOC entry 3394 (class 2606 OID 24404)
-- Name: tab_user un_email_tab_user; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_user
    ADD CONSTRAINT un_email_tab_user UNIQUE (email);


--
-- TOC entry 3378 (class 2606 OID 24369)
-- Name: tab_student un_enrollment_tab_student; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_student
    ADD CONSTRAINT un_enrollment_tab_student UNIQUE (enrollment);


--
-- TOC entry 3360 (class 2606 OID 24328)
-- Name: tab_professor un_institutional_email_tab_professor; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_professor
    ADD CONSTRAINT un_institutional_email_tab_professor UNIQUE (institutional_email);


--
-- TOC entry 3380 (class 2606 OID 24371)
-- Name: tab_student un_institutional_email_tab_student; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_student
    ADD CONSTRAINT un_institutional_email_tab_student UNIQUE (institutional_email);


--
-- TOC entry 3374 (class 2606 OID 24360)
-- Name: tab_public_servant_role un_role_tab_public_servant_role; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_public_servant_role
    ADD CONSTRAINT un_role_tab_public_servant_role UNIQUE (role);


--
-- TOC entry 3402 (class 2606 OID 24419)
-- Name: tab_user_role un_role_tab_user_role; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_user_role
    ADD CONSTRAINT un_role_tab_user_role UNIQUE (role);


--
-- TOC entry 3368 (class 2606 OID 24346)
-- Name: tab_public_servant un_siape_tab_public_servant; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_public_servant
    ADD CONSTRAINT un_siape_tab_public_servant UNIQUE (siape);


--
-- TOC entry 3396 (class 2606 OID 24406)
-- Name: tab_user un_username_tab_user; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_user
    ADD CONSTRAINT un_username_tab_user UNIQUE (username);


--
-- TOC entry 3418 (class 2606 OID 24495)
-- Name: tab_professor fk18m0jps0jn9vd0r5hi27m5jbf; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_professor
    ADD CONSTRAINT fk18m0jps0jn9vd0r5hi27m5jbf FOREIGN KEY (id) REFERENCES public.tab_public_servant(id);


--
-- TOC entry 3405 (class 2606 OID 24430)
-- Name: tab_administrative_public_servant fk1jryfbax0cbastspphp2s1yli; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_administrative_public_servant
    ADD CONSTRAINT fk1jryfbax0cbastspphp2s1yli FOREIGN KEY (id) REFERENCES public.tab_public_servant(id);


--
-- TOC entry 3423 (class 2606 OID 24520)
-- Name: tab_public_servant_has_role fk28kunwve6203qyvtdvnu03fyh; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_public_servant_has_role
    ADD CONSTRAINT fk28kunwve6203qyvtdvnu03fyh FOREIGN KEY (public_servant_role_id) REFERENCES public.tab_public_servant_role(id);


--
-- TOC entry 3431 (class 2606 OID 24560)
-- Name: tab_user_has_role fk2rh2wh387ytycggdep21jm56w; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_user_has_role
    ADD CONSTRAINT fk2rh2wh387ytycggdep21jm56w FOREIGN KEY (user_role_id) REFERENCES public.tab_user_role(id);


--
-- TOC entry 3421 (class 2606 OID 24515)
-- Name: tab_public_servant fk2wa60h58oms8crh3o31ufm21w; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_public_servant
    ADD CONSTRAINT fk2wa60h58oms8crh3o31ufm21w FOREIGN KEY (id) REFERENCES public.tab_affiliation(id);


--
-- TOC entry 3427 (class 2606 OID 24540)
-- Name: tab_student_groups fk381mmqimieo8pchr7j7woa27j; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_student_groups
    ADD CONSTRAINT fk381mmqimieo8pchr7j7woa27j FOREIGN KEY (groups_id) REFERENCES public.tab_group(id);


--
-- TOC entry 3422 (class 2606 OID 24510)
-- Name: tab_public_servant fk3f8ktc5w77g1387el2ixgsrud; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_public_servant
    ADD CONSTRAINT fk3f8ktc5w77g1387el2ixgsrud FOREIGN KEY (dapartment_id) REFERENCES public.tab_department(id);


--
-- TOC entry 3429 (class 2606 OID 24555)
-- Name: tab_subject_courses fk4voxttsubnvxsanrloncfdte4; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_subject_courses
    ADD CONSTRAINT fk4voxttsubnvxsanrloncfdte4 FOREIGN KEY (subject_id) REFERENCES public.tab_subject(id);


--
-- TOC entry 3403 (class 2606 OID 24425)
-- Name: group_id fk5t8gir3pyqenis1y0fd5jf40u; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.group_id
    ADD CONSTRAINT fk5t8gir3pyqenis1y0fd5jf40u FOREIGN KEY (id) REFERENCES public.tab_lesson_reservation(id);


--
-- TOC entry 3419 (class 2606 OID 24500)
-- Name: tab_professor_groups fk60byudwyqjojjbpfrq0gxt7lh; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_professor_groups
    ADD CONSTRAINT fk60byudwyqjojjbpfrq0gxt7lh FOREIGN KEY (groups_id) REFERENCES public.tab_group(id);


--
-- TOC entry 3425 (class 2606 OID 24535)
-- Name: tab_student fk6gmffoak7cnus601930h4w35i; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_student
    ADD CONSTRAINT fk6gmffoak7cnus601930h4w35i FOREIGN KEY (id) REFERENCES public.tab_affiliation(id);


--
-- TOC entry 3414 (class 2606 OID 24475)
-- Name: tab_group_has_student fk6vr44uocv30otsyoys48i1uwr; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_group_has_student
    ADD CONSTRAINT fk6vr44uocv30otsyoys48i1uwr FOREIGN KEY (students_id) REFERENCES public.tab_student(id);


--
-- TOC entry 3420 (class 2606 OID 24505)
-- Name: tab_professor_groups fk7848splvy1qa3esdjfusmjciu; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_professor_groups
    ADD CONSTRAINT fk7848splvy1qa3esdjfusmjciu FOREIGN KEY (professor_id) REFERENCES public.tab_professor(id);


--
-- TOC entry 3407 (class 2606 OID 24440)
-- Name: tab_classroom fk8aafk0xmbyu17bgg5x0h609o; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_classroom
    ADD CONSTRAINT fk8aafk0xmbyu17bgg5x0h609o FOREIGN KEY (id) REFERENCES public.tab_internal_room(id);


--
-- TOC entry 3404 (class 2606 OID 24420)
-- Name: group_id fkc0ohkp7obd10nxmv6e5p2vrvc; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.group_id
    ADD CONSTRAINT fkc0ohkp7obd10nxmv6e5p2vrvc FOREIGN KEY (group_id) REFERENCES public.tab_group(id);


--
-- TOC entry 3411 (class 2606 OID 24460)
-- Name: tab_group fkdqp8ngpf9qd3js484ihqroonu; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_group
    ADD CONSTRAINT fkdqp8ngpf9qd3js484ihqroonu FOREIGN KEY (subject_id) REFERENCES public.tab_subject(id);


--
-- TOC entry 3430 (class 2606 OID 24550)
-- Name: tab_subject_courses fke9291aaoguocsmhtb7tx0y1v0; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_subject_courses
    ADD CONSTRAINT fke9291aaoguocsmhtb7tx0y1v0 FOREIGN KEY (courses_id) REFERENCES public.tab_course(id);


--
-- TOC entry 3412 (class 2606 OID 24465)
-- Name: tab_group_has_professor fked93l5srvpvt2opyqkujyamwu; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_group_has_professor
    ADD CONSTRAINT fked93l5srvpvt2opyqkujyamwu FOREIGN KEY (professors_id) REFERENCES public.tab_professor(id);


--
-- TOC entry 3416 (class 2606 OID 24485)
-- Name: tab_internal_room fkehpfkbxkw0lbrk6rv4ax40nn; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_internal_room
    ADD CONSTRAINT fkehpfkbxkw0lbrk6rv4ax40nn FOREIGN KEY (building_id) REFERENCES public.tab_building(id);


--
-- TOC entry 3417 (class 2606 OID 24490)
-- Name: tab_lesson_reservation fkei635p6q95hm1siedyg08t6ui; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_lesson_reservation
    ADD CONSTRAINT fkei635p6q95hm1siedyg08t6ui FOREIGN KEY (classroom_id) REFERENCES public.tab_classroom(id);


--
-- TOC entry 3406 (class 2606 OID 24435)
-- Name: tab_affiliation fkgu6awqwjmr1itpkb4p73q4li3; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_affiliation
    ADD CONSTRAINT fkgu6awqwjmr1itpkb4p73q4li3 FOREIGN KEY (user_id) REFERENCES public.tab_user(id);


--
-- TOC entry 3413 (class 2606 OID 24470)
-- Name: tab_group_has_professor fkhfce4yubpknsdt3gw2dkw3671; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_group_has_professor
    ADD CONSTRAINT fkhfce4yubpknsdt3gw2dkw3671 FOREIGN KEY (group_id) REFERENCES public.tab_group(id);


--
-- TOC entry 3408 (class 2606 OID 24445)
-- Name: tab_computer_laboratory fkk20ewkmjhbvc1t2jul612i20n; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_computer_laboratory
    ADD CONSTRAINT fkk20ewkmjhbvc1t2jul612i20n FOREIGN KEY (id) REFERENCES public.tab_internal_room(id);


--
-- TOC entry 3409 (class 2606 OID 24450)
-- Name: tab_course_has_subject fkknr885u448h7goh7ho96qd24; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_course_has_subject
    ADD CONSTRAINT fkknr885u448h7goh7ho96qd24 FOREIGN KEY (subjects_id) REFERENCES public.tab_subject(id);


--
-- TOC entry 3424 (class 2606 OID 24525)
-- Name: tab_public_servant_has_role fkl226xgouagx2so99rg6cyxjpr; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_public_servant_has_role
    ADD CONSTRAINT fkl226xgouagx2so99rg6cyxjpr FOREIGN KEY (public_servant_id) REFERENCES public.tab_public_servant(id);


--
-- TOC entry 3410 (class 2606 OID 24455)
-- Name: tab_course_has_subject fkm39u6ad9raw3qojaskwv64xx7; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_course_has_subject
    ADD CONSTRAINT fkm39u6ad9raw3qojaskwv64xx7 FOREIGN KEY (course_id) REFERENCES public.tab_course(id);


--
-- TOC entry 3428 (class 2606 OID 24545)
-- Name: tab_student_groups fknejmpk5li8yo1kfn8n7u4slh5; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_student_groups
    ADD CONSTRAINT fknejmpk5li8yo1kfn8n7u4slh5 FOREIGN KEY (student_id) REFERENCES public.tab_student(id);


--
-- TOC entry 3426 (class 2606 OID 24530)
-- Name: tab_student fkofyng9cuud38t4bewdlhqoc37; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_student
    ADD CONSTRAINT fkofyng9cuud38t4bewdlhqoc37 FOREIGN KEY (course_id) REFERENCES public.tab_course(id);


--
-- TOC entry 3415 (class 2606 OID 24480)
-- Name: tab_group_has_student fksk2391mq2qu89jewybwcktda6; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_group_has_student
    ADD CONSTRAINT fksk2391mq2qu89jewybwcktda6 FOREIGN KEY (group_id) REFERENCES public.tab_group(id);


--
-- TOC entry 3432 (class 2606 OID 24565)
-- Name: tab_user_has_role fkssrounfohxjwa2mcsko8r339n; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_user_has_role
    ADD CONSTRAINT fkssrounfohxjwa2mcsko8r339n FOREIGN KEY (user_id) REFERENCES public.tab_user(id);


-- Completed on 2024-12-05 19:39:18 UTC

--
-- PostgreSQL database dump complete
--

