--
-- PostgreSQL database dump
--

-- Dumped from database version 17.2 (Debian 17.2-1.pgdg120+1)
-- Dumped by pg_dump version 17.2

-- Started on 2024-12-20 01:54:05 UTC

-- SET statement_timeout = 0;
-- SET lock_timeout = 0;
-- SET idle_in_transaction_session_timeout = 0;
-- SET transaction_timeout = 0;
-- SET client_encoding = 'UTF8';
-- SET standard_conforming_strings = on;
-- SELECT pg_catalog.set_config('search_path', '', false);
-- SET check_function_bodies = false;
-- SET xmloption = content;
-- SET client_min_messages = warning;
-- SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

-- CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 3615 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 217 (class 1259 OID 36520)
-- Name: tab_administrative_public_servant; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tab_administrative_public_servant (
                                                          affiliation_id uuid NOT NULL
);


ALTER TABLE public.tab_administrative_public_servant OWNER TO admin;

--
-- TOC entry 218 (class 1259 OID 36525)
-- Name: tab_affiliation; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tab_affiliation (
                                        ending_date date,
                                        starting_date date NOT NULL,
                                        created_at timestamp(6) without time zone,
                                        id uuid NOT NULL,
                                        user_id uuid,
                                        status character varying(255) NOT NULL,
                                        CONSTRAINT tab_affiliation_status_check CHECK (((status)::text = ANY ((ARRAY['CREATED'::character varying, 'ACTIVE'::character varying, 'SUSPENDED'::character varying, 'FINISHED'::character varying])::text[])))
);


ALTER TABLE public.tab_affiliation OWNER TO admin;

--
-- TOC entry 220 (class 1259 OID 36532)
-- Name: tab_building; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tab_building (
                                     type smallint,
                                     id bigint NOT NULL,
                                     code character varying(255),
                                     CONSTRAINT tab_building_type_check CHECK (((type >= 0) AND (type <= 4)))
);


ALTER TABLE public.tab_building OWNER TO admin;

--
-- TOC entry 219 (class 1259 OID 36531)
-- Name: tab_building_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.tab_building ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tab_building_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 36538)
-- Name: tab_classroom; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tab_classroom (
                                      status smallint,
                                      id uuid NOT NULL,
                                      code character varying(255),
                                      CONSTRAINT tab_classroom_status_check CHECK (((status >= 0) AND (status <= 3)))
);


ALTER TABLE public.tab_classroom OWNER TO admin;

--
-- TOC entry 222 (class 1259 OID 36544)
-- Name: tab_computer_laboratory; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tab_computer_laboratory (
                                                status smallint,
                                                id uuid NOT NULL,
                                                code character varying(255),
                                                CONSTRAINT tab_computer_laboratory_status_check CHECK (((status >= 0) AND (status <= 3)))
);


ALTER TABLE public.tab_computer_laboratory OWNER TO admin;

--
-- TOC entry 223 (class 1259 OID 36550)
-- Name: tab_course; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tab_course (
                                   quantity_of_semesters integer,
                                   id uuid NOT NULL,
                                   code character varying(255),
                                   short_title character varying(255),
                                   title character varying(255),
                                   type character varying(255),
                                   CONSTRAINT tab_course_type_check CHECK (((type)::text = ANY ((ARRAY['BACHELOR'::character varying, 'LICENTIATE'::character varying, 'SUBSEQUENT'::character varying, 'INTEGRATED'::character varying, 'MASTER'::character varying, 'DOCTORATE'::character varying, 'POSTGRADUATE'::character varying, 'EXTENSION'::character varying, 'SPECIALIZATION'::character varying, 'TECHNICAL'::character varying])::text[])))
);


ALTER TABLE public.tab_course OWNER TO admin;

--
-- TOC entry 224 (class 1259 OID 36558)
-- Name: tab_course_calendar; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tab_course_calendar (
                                            id uuid NOT NULL,
                                            title character varying(255)
);


ALTER TABLE public.tab_course_calendar OWNER TO admin;

--
-- TOC entry 225 (class 1259 OID 36563)
-- Name: tab_course_has_subject; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tab_course_has_subject (
                                               course_id uuid NOT NULL,
                                               subjects_id uuid NOT NULL
);


ALTER TABLE public.tab_course_has_subject OWNER TO admin;

--
-- TOC entry 226 (class 1259 OID 36568)
-- Name: tab_department; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tab_department (
                                       id uuid NOT NULL,
                                       code character varying(255) NOT NULL,
                                       name character varying(255) NOT NULL
);


ALTER TABLE public.tab_department OWNER TO admin;

--
-- TOC entry 227 (class 1259 OID 36577)
-- Name: tab_group; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tab_group (
                                  academic_year integer,
                                  created_at timestamp(6) without time zone,
                                  id uuid NOT NULL,
                                  subject_id uuid,
                                  academic_semester character varying(255),
                                  code character varying(255),
                                  status character varying(255),
                                  CONSTRAINT tab_group_academic_semester_check CHECK (((academic_semester)::text = ANY ((ARRAY['FIRST_SEMESTER'::character varying, 'SECOND_SEMESTER'::character varying])::text[]))),
    CONSTRAINT tab_group_status_check CHECK (((status)::text = ANY ((ARRAY['OPEN'::character varying, 'ACTIVE'::character varying, 'CLOSED'::character varying])::text[])))
);


ALTER TABLE public.tab_group OWNER TO admin;

--
-- TOC entry 228 (class 1259 OID 36586)
-- Name: tab_group_has_professor; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tab_group_has_professor (
                                                group_id uuid NOT NULL,
                                                professors_affiliation_id uuid NOT NULL
);


ALTER TABLE public.tab_group_has_professor OWNER TO admin;

--
-- TOC entry 229 (class 1259 OID 36591)
-- Name: tab_group_has_student; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tab_group_has_student (
                                              group_id uuid NOT NULL,
                                              students_affiliation_id uuid NOT NULL
);


ALTER TABLE public.tab_group_has_student OWNER TO admin;

--
-- TOC entry 230 (class 1259 OID 36596)
-- Name: tab_internal_room; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tab_internal_room (
                                          building_id bigint,
                                          id uuid NOT NULL,
                                          observations character varying(255)
);


ALTER TABLE public.tab_internal_room OWNER TO admin;

--
-- TOC entry 231 (class 1259 OID 36601)
-- Name: tab_lesson_reservation; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tab_lesson_reservation (
                                               day smallint,
                                               ending_time time(6) without time zone,
                                               starting_time time(6) without time zone,
                                               classroom_id uuid,
                                               group_id uuid,
                                               id uuid NOT NULL,
                                               CONSTRAINT tab_lesson_reservation_day_check CHECK (((day >= 0) AND (day <= 6)))
);


ALTER TABLE public.tab_lesson_reservation OWNER TO admin;

--
-- TOC entry 232 (class 1259 OID 36607)
-- Name: tab_professor; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tab_professor (
                                      affiliation_id uuid NOT NULL,
                                      institutional_email character varying(255) NOT NULL
);


ALTER TABLE public.tab_professor OWNER TO admin;

--
-- TOC entry 233 (class 1259 OID 36614)
-- Name: tab_professor_calendar; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tab_professor_calendar (
                                               id uuid NOT NULL,
                                               title character varying(255)
);


ALTER TABLE public.tab_professor_calendar OWNER TO admin;

--
-- TOC entry 234 (class 1259 OID 36619)
-- Name: tab_professor_groups; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tab_professor_groups (
                                             groups_id uuid NOT NULL,
                                             professor_affiliation_id uuid NOT NULL
);


ALTER TABLE public.tab_professor_groups OWNER TO admin;

--
-- TOC entry 235 (class 1259 OID 36624)
-- Name: tab_public_servant; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tab_public_servant (
                                           affiliation_id uuid NOT NULL,
                                           department_id uuid,
                                           education_level character varying(255) NOT NULL,
                                           siape character varying(255) NOT NULL,
                                           CONSTRAINT tab_public_servant_education_level_check CHECK (((education_level)::text = ANY ((ARRAY['HIGH_SCHOOL'::character varying, 'TECHNICAL_CERTIFICATION'::character varying, 'ASSOCIATE'::character varying, 'BACHELOR_EDUCATION'::character varying, 'BACHELOR'::character varying, 'POSTGRADUATE'::character varying, 'MASTER'::character varying, 'DOCTORATE'::character varying, 'POST_DOCTORATE'::character varying])::text[])))
);


ALTER TABLE public.tab_public_servant OWNER TO admin;

--
-- TOC entry 236 (class 1259 OID 36634)
-- Name: tab_public_servant_has_role; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tab_public_servant_has_role (
                                                    public_servant_role_id bigint NOT NULL,
                                                    public_servant_id uuid NOT NULL
);


ALTER TABLE public.tab_public_servant_has_role OWNER TO admin;

--
-- TOC entry 238 (class 1259 OID 36640)
-- Name: tab_public_servant_role; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tab_public_servant_role (
                                                id bigint NOT NULL,
                                                role character varying(255) NOT NULL,
                                                CONSTRAINT tab_public_servant_role_role_check CHECK (((role)::text = 'COURSE_COORDINATOR'::text))
);


ALTER TABLE public.tab_public_servant_role OWNER TO admin;

--
-- TOC entry 237 (class 1259 OID 36639)
-- Name: tab_public_servant_role_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.tab_public_servant_role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tab_public_servant_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 239 (class 1259 OID 36648)
-- Name: tab_student; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tab_student (
                                    affiliation_id uuid NOT NULL,
                                    course_id uuid,
                                    enrollment character varying(255) NOT NULL,
                                    institutional_email character varying(255) NOT NULL
);


ALTER TABLE public.tab_student OWNER TO admin;

--
-- TOC entry 240 (class 1259 OID 36659)
-- Name: tab_student_calendar; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tab_student_calendar (
                                             id uuid NOT NULL,
                                             title character varying(255)
);


ALTER TABLE public.tab_student_calendar OWNER TO admin;

--
-- TOC entry 241 (class 1259 OID 36664)
-- Name: tab_student_groups; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tab_student_groups (
                                           groups_id uuid NOT NULL,
                                           student_affiliation_id uuid NOT NULL
);


ALTER TABLE public.tab_student_groups OWNER TO admin;

--
-- TOC entry 242 (class 1259 OID 36669)
-- Name: tab_subject; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tab_subject (
                                    created_at timestamp(6) without time zone,
                                    id uuid NOT NULL,
                                    code character varying(255),
                                    short_title character varying(255),
                                    title character varying(255)
);


ALTER TABLE public.tab_subject OWNER TO admin;

--
-- TOC entry 243 (class 1259 OID 36676)
-- Name: tab_subject_courses; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tab_subject_courses (
                                            courses_id uuid NOT NULL,
                                            subject_id uuid NOT NULL
);


ALTER TABLE public.tab_subject_courses OWNER TO admin;

--
-- TOC entry 244 (class 1259 OID 36681)
-- Name: tab_user; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tab_user (
                                 birthdate date NOT NULL,
                                 created_at timestamp(6) without time zone NOT NULL,
                                 id uuid NOT NULL,
                                 password character varying(100) NOT NULL,
                                 cpf character varying(255) NOT NULL,
                                 email character varying(255) NOT NULL,
                                 name character varying(255) NOT NULL,
                                 surname character varying(255) NOT NULL,
                                 username character varying(255) NOT NULL
);


ALTER TABLE public.tab_user OWNER TO admin;

--
-- TOC entry 245 (class 1259 OID 36694)
-- Name: tab_user_has_role; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tab_user_has_role (
                                          user_role_id integer NOT NULL,
                                          user_id uuid NOT NULL
);


ALTER TABLE public.tab_user_has_role OWNER TO admin;

--
-- TOC entry 246 (class 1259 OID 36699)
-- Name: tab_user_role; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tab_user_role (
                                      id integer NOT NULL,
                                      role character varying(255) NOT NULL,
                                      CONSTRAINT tab_user_role_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'USER'::character varying])::text[])))
);


ALTER TABLE public.tab_user_role OWNER TO admin;

--
-- TOC entry 3580 (class 0 OID 36520)
-- Dependencies: 217
-- Data for Name: tab_administrative_public_servant; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.tab_administrative_public_servant (affiliation_id) FROM stdin;
\.


--
-- TOC entry 3581 (class 0 OID 36525)
-- Dependencies: 218
-- Data for Name: tab_affiliation; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.tab_affiliation (ending_date, starting_date, created_at, id, user_id, status) FROM stdin;
\.


--
-- TOC entry 3583 (class 0 OID 36532)
-- Dependencies: 220
-- Data for Name: tab_building; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.tab_building (type, id, code) FROM stdin;
\.


--
-- TOC entry 3584 (class 0 OID 36538)
-- Dependencies: 221
-- Data for Name: tab_classroom; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.tab_classroom (status, id, code) FROM stdin;
\.


--
-- TOC entry 3585 (class 0 OID 36544)
-- Dependencies: 222
-- Data for Name: tab_computer_laboratory; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.tab_computer_laboratory (status, id, code) FROM stdin;
\.


--
-- TOC entry 3586 (class 0 OID 36550)
-- Dependencies: 223
-- Data for Name: tab_course; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.tab_course (quantity_of_semesters, id, code, short_title, title, type) FROM stdin;
\.


--
-- TOC entry 3587 (class 0 OID 36558)
-- Dependencies: 224
-- Data for Name: tab_course_calendar; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.tab_course_calendar (id, title) FROM stdin;
\.


--
-- TOC entry 3588 (class 0 OID 36563)
-- Dependencies: 225
-- Data for Name: tab_course_has_subject; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.tab_course_has_subject (course_id, subjects_id) FROM stdin;
\.


--
-- TOC entry 3589 (class 0 OID 36568)
-- Dependencies: 226
-- Data for Name: tab_department; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.tab_department (id, code, name) FROM stdin;
\.


--
-- TOC entry 3590 (class 0 OID 36577)
-- Dependencies: 227
-- Data for Name: tab_group; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.tab_group (academic_year, created_at, id, subject_id, academic_semester, code, status) FROM stdin;
\.


--
-- TOC entry 3591 (class 0 OID 36586)
-- Dependencies: 228
-- Data for Name: tab_group_has_professor; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.tab_group_has_professor (group_id, professors_affiliation_id) FROM stdin;
\.


--
-- TOC entry 3592 (class 0 OID 36591)
-- Dependencies: 229
-- Data for Name: tab_group_has_student; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.tab_group_has_student (group_id, students_affiliation_id) FROM stdin;
\.


--
-- TOC entry 3593 (class 0 OID 36596)
-- Dependencies: 230
-- Data for Name: tab_internal_room; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.tab_internal_room (building_id, id, observations) FROM stdin;
\.


--
-- TOC entry 3594 (class 0 OID 36601)
-- Dependencies: 231
-- Data for Name: tab_lesson_reservation; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.tab_lesson_reservation (day, ending_time, starting_time, classroom_id, group_id, id) FROM stdin;
\.


--
-- TOC entry 3595 (class 0 OID 36607)
-- Dependencies: 232
-- Data for Name: tab_professor; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.tab_professor (affiliation_id, institutional_email) FROM stdin;
\.


--
-- TOC entry 3596 (class 0 OID 36614)
-- Dependencies: 233
-- Data for Name: tab_professor_calendar; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.tab_professor_calendar (id, title) FROM stdin;
\.


--
-- TOC entry 3597 (class 0 OID 36619)
-- Dependencies: 234
-- Data for Name: tab_professor_groups; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.tab_professor_groups (groups_id, professor_affiliation_id) FROM stdin;
\.


--
-- TOC entry 3598 (class 0 OID 36624)
-- Dependencies: 235
-- Data for Name: tab_public_servant; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.tab_public_servant (affiliation_id, department_id, education_level, siape) FROM stdin;
\.


--
-- TOC entry 3599 (class 0 OID 36634)
-- Dependencies: 236
-- Data for Name: tab_public_servant_has_role; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.tab_public_servant_has_role (public_servant_role_id, public_servant_id) FROM stdin;
\.


--
-- TOC entry 3601 (class 0 OID 36640)
-- Dependencies: 238
-- Data for Name: tab_public_servant_role; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.tab_public_servant_role (id, role) FROM stdin;
\.


--
-- TOC entry 3602 (class 0 OID 36648)
-- Dependencies: 239
-- Data for Name: tab_student; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.tab_student (affiliation_id, course_id, enrollment, institutional_email) FROM stdin;
\.


--
-- TOC entry 3603 (class 0 OID 36659)
-- Dependencies: 240
-- Data for Name: tab_student_calendar; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.tab_student_calendar (id, title) FROM stdin;
\.


--
-- TOC entry 3604 (class 0 OID 36664)
-- Dependencies: 241
-- Data for Name: tab_student_groups; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.tab_student_groups (groups_id, student_affiliation_id) FROM stdin;
\.


--
-- TOC entry 3605 (class 0 OID 36669)
-- Dependencies: 242
-- Data for Name: tab_subject; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.tab_subject (created_at, id, code, short_title, title) FROM stdin;
\.


--
-- TOC entry 3606 (class 0 OID 36676)
-- Dependencies: 243
-- Data for Name: tab_subject_courses; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.tab_subject_courses (courses_id, subject_id) FROM stdin;
\.


--
-- TOC entry 3607 (class 0 OID 36681)
-- Dependencies: 244
-- Data for Name: tab_user; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.tab_user (birthdate, created_at, id, password, cpf, email, name, surname, username) FROM stdin;
\.


--
-- TOC entry 3608 (class 0 OID 36694)
-- Dependencies: 245
-- Data for Name: tab_user_has_role; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.tab_user_has_role (user_role_id, user_id) FROM stdin;
\.


--
-- TOC entry 3609 (class 0 OID 36699)
-- Dependencies: 246
-- Data for Name: tab_user_role; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.tab_user_role (id, role) FROM stdin;
\.


--
-- TOC entry 3616 (class 0 OID 0)
-- Dependencies: 219
-- Name: tab_building_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.tab_building_id_seq', 1, false);


--
-- TOC entry 3617 (class 0 OID 0)
-- Dependencies: 237
-- Name: tab_public_servant_role_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.tab_public_servant_role_id_seq', 1, false);


--
-- TOC entry 3331 (class 2606 OID 36524)
-- Name: tab_administrative_public_servant tab_administrative_public_servant_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_administrative_public_servant
    ADD CONSTRAINT tab_administrative_public_servant_pkey PRIMARY KEY (affiliation_id);


--
-- TOC entry 3333 (class 2606 OID 36530)
-- Name: tab_affiliation tab_affiliation_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_affiliation
    ADD CONSTRAINT tab_affiliation_pkey PRIMARY KEY (id);


--
-- TOC entry 3335 (class 2606 OID 36537)
-- Name: tab_building tab_building_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_building
    ADD CONSTRAINT tab_building_pkey PRIMARY KEY (id);


--
-- TOC entry 3337 (class 2606 OID 36543)
-- Name: tab_classroom tab_classroom_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_classroom
    ADD CONSTRAINT tab_classroom_pkey PRIMARY KEY (id);


--
-- TOC entry 3339 (class 2606 OID 36549)
-- Name: tab_computer_laboratory tab_computer_laboratory_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_computer_laboratory
    ADD CONSTRAINT tab_computer_laboratory_pkey PRIMARY KEY (id);


--
-- TOC entry 3343 (class 2606 OID 36562)
-- Name: tab_course_calendar tab_course_calendar_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_course_calendar
    ADD CONSTRAINT tab_course_calendar_pkey PRIMARY KEY (id);


--
-- TOC entry 3345 (class 2606 OID 36567)
-- Name: tab_course_has_subject tab_course_has_subject_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_course_has_subject
    ADD CONSTRAINT tab_course_has_subject_pkey PRIMARY KEY (course_id, subjects_id);


--
-- TOC entry 3341 (class 2606 OID 36557)
-- Name: tab_course tab_course_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_course
    ADD CONSTRAINT tab_course_pkey PRIMARY KEY (id);


--
-- TOC entry 3347 (class 2606 OID 36574)
-- Name: tab_department tab_department_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_department
    ADD CONSTRAINT tab_department_pkey PRIMARY KEY (id);


--
-- TOC entry 3353 (class 2606 OID 36590)
-- Name: tab_group_has_professor tab_group_has_professor_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_group_has_professor
    ADD CONSTRAINT tab_group_has_professor_pkey PRIMARY KEY (group_id, professors_affiliation_id);


--
-- TOC entry 3355 (class 2606 OID 36595)
-- Name: tab_group_has_student tab_group_has_student_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_group_has_student
    ADD CONSTRAINT tab_group_has_student_pkey PRIMARY KEY (group_id, students_affiliation_id);


--
-- TOC entry 3351 (class 2606 OID 36585)
-- Name: tab_group tab_group_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_group
    ADD CONSTRAINT tab_group_pkey PRIMARY KEY (id);


--
-- TOC entry 3357 (class 2606 OID 36600)
-- Name: tab_internal_room tab_internal_room_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_internal_room
    ADD CONSTRAINT tab_internal_room_pkey PRIMARY KEY (id);


--
-- TOC entry 3359 (class 2606 OID 36606)
-- Name: tab_lesson_reservation tab_lesson_reservation_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_lesson_reservation
    ADD CONSTRAINT tab_lesson_reservation_pkey PRIMARY KEY (id);


--
-- TOC entry 3365 (class 2606 OID 36618)
-- Name: tab_professor_calendar tab_professor_calendar_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_professor_calendar
    ADD CONSTRAINT tab_professor_calendar_pkey PRIMARY KEY (id);


--
-- TOC entry 3367 (class 2606 OID 36623)
-- Name: tab_professor_groups tab_professor_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_professor_groups
    ADD CONSTRAINT tab_professor_groups_pkey PRIMARY KEY (groups_id, professor_affiliation_id);


--
-- TOC entry 3361 (class 2606 OID 36611)
-- Name: tab_professor tab_professor_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_professor
    ADD CONSTRAINT tab_professor_pkey PRIMARY KEY (affiliation_id);


--
-- TOC entry 3373 (class 2606 OID 36638)
-- Name: tab_public_servant_has_role tab_public_servant_has_role_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_public_servant_has_role
    ADD CONSTRAINT tab_public_servant_has_role_pkey PRIMARY KEY (public_servant_role_id, public_servant_id);


--
-- TOC entry 3369 (class 2606 OID 36631)
-- Name: tab_public_servant tab_public_servant_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_public_servant
    ADD CONSTRAINT tab_public_servant_pkey PRIMARY KEY (affiliation_id);


--
-- TOC entry 3375 (class 2606 OID 36645)
-- Name: tab_public_servant_role tab_public_servant_role_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_public_servant_role
    ADD CONSTRAINT tab_public_servant_role_pkey PRIMARY KEY (id);


--
-- TOC entry 3385 (class 2606 OID 36663)
-- Name: tab_student_calendar tab_student_calendar_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_student_calendar
    ADD CONSTRAINT tab_student_calendar_pkey PRIMARY KEY (id);


--
-- TOC entry 3387 (class 2606 OID 36668)
-- Name: tab_student_groups tab_student_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_student_groups
    ADD CONSTRAINT tab_student_groups_pkey PRIMARY KEY (groups_id, student_affiliation_id);


--
-- TOC entry 3379 (class 2606 OID 36654)
-- Name: tab_student tab_student_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_student
    ADD CONSTRAINT tab_student_pkey PRIMARY KEY (affiliation_id);


--
-- TOC entry 3391 (class 2606 OID 36680)
-- Name: tab_subject_courses tab_subject_courses_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_subject_courses
    ADD CONSTRAINT tab_subject_courses_pkey PRIMARY KEY (courses_id, subject_id);


--
-- TOC entry 3389 (class 2606 OID 36675)
-- Name: tab_subject tab_subject_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_subject
    ADD CONSTRAINT tab_subject_pkey PRIMARY KEY (id);


--
-- TOC entry 3401 (class 2606 OID 36698)
-- Name: tab_user_has_role tab_user_has_role_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_user_has_role
    ADD CONSTRAINT tab_user_has_role_pkey PRIMARY KEY (user_role_id, user_id);


--
-- TOC entry 3393 (class 2606 OID 36687)
-- Name: tab_user tab_user_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_user
    ADD CONSTRAINT tab_user_pkey PRIMARY KEY (id);


--
-- TOC entry 3403 (class 2606 OID 36704)
-- Name: tab_user_role tab_user_role_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_user_role
    ADD CONSTRAINT tab_user_role_pkey PRIMARY KEY (id);


--
-- TOC entry 3349 (class 2606 OID 36576)
-- Name: tab_department un_code_tab_department; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_department
    ADD CONSTRAINT un_code_tab_department UNIQUE (code);


--
-- TOC entry 3395 (class 2606 OID 36689)
-- Name: tab_user un_cpf_tab_user; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_user
    ADD CONSTRAINT un_cpf_tab_user UNIQUE (cpf);


--
-- TOC entry 3397 (class 2606 OID 36691)
-- Name: tab_user un_email_tab_user; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_user
    ADD CONSTRAINT un_email_tab_user UNIQUE (email);


--
-- TOC entry 3381 (class 2606 OID 36656)
-- Name: tab_student un_enrollment_tab_student; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_student
    ADD CONSTRAINT un_enrollment_tab_student UNIQUE (enrollment);


--
-- TOC entry 3363 (class 2606 OID 36613)
-- Name: tab_professor un_institutional_email_tab_professor; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_professor
    ADD CONSTRAINT un_institutional_email_tab_professor UNIQUE (institutional_email);


--
-- TOC entry 3383 (class 2606 OID 36658)
-- Name: tab_student un_institutional_email_tab_student; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_student
    ADD CONSTRAINT un_institutional_email_tab_student UNIQUE (institutional_email);


--
-- TOC entry 3377 (class 2606 OID 36647)
-- Name: tab_public_servant_role un_role_tab_public_servant_role; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_public_servant_role
    ADD CONSTRAINT un_role_tab_public_servant_role UNIQUE (role);


--
-- TOC entry 3405 (class 2606 OID 36706)
-- Name: tab_user_role un_role_tab_user_role; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_user_role
    ADD CONSTRAINT un_role_tab_user_role UNIQUE (role);


--
-- TOC entry 3371 (class 2606 OID 36633)
-- Name: tab_public_servant un_siape_tab_public_servant; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_public_servant
    ADD CONSTRAINT un_siape_tab_public_servant UNIQUE (siape);


--
-- TOC entry 3399 (class 2606 OID 36693)
-- Name: tab_user un_username_tab_user; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_user
    ADD CONSTRAINT un_username_tab_user UNIQUE (username);


--
-- TOC entry 3425 (class 2606 OID 36802)
-- Name: tab_public_servant_has_role fk28kunwve6203qyvtdvnu03fyh; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_public_servant_has_role
    ADD CONSTRAINT fk28kunwve6203qyvtdvnu03fyh FOREIGN KEY (public_servant_role_id) REFERENCES public.tab_public_servant_role(id);


--
-- TOC entry 3418 (class 2606 OID 36772)
-- Name: tab_lesson_reservation fk2khouw6jfd92fxg9o9ra96av3; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_lesson_reservation
    ADD CONSTRAINT fk2khouw6jfd92fxg9o9ra96av3 FOREIGN KEY (group_id) REFERENCES public.tab_group(id);


--
-- TOC entry 3433 (class 2606 OID 36842)
-- Name: tab_user_has_role fk2rh2wh387ytycggdep21jm56w; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_user_has_role
    ADD CONSTRAINT fk2rh2wh387ytycggdep21jm56w FOREIGN KEY (user_role_id) REFERENCES public.tab_user_role(id);


--
-- TOC entry 3429 (class 2606 OID 36822)
-- Name: tab_student_groups fk381mmqimieo8pchr7j7woa27j; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_student_groups
    ADD CONSTRAINT fk381mmqimieo8pchr7j7woa27j FOREIGN KEY (groups_id) REFERENCES public.tab_group(id);


--
-- TOC entry 3430 (class 2606 OID 36827)
-- Name: tab_student_groups fk3ojyqfxct6om9meksvi09q0q3; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_student_groups
    ADD CONSTRAINT fk3ojyqfxct6om9meksvi09q0q3 FOREIGN KEY (student_affiliation_id) REFERENCES public.tab_student(affiliation_id);


--
-- TOC entry 3431 (class 2606 OID 36837)
-- Name: tab_subject_courses fk4voxttsubnvxsanrloncfdte4; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_subject_courses
    ADD CONSTRAINT fk4voxttsubnvxsanrloncfdte4 FOREIGN KEY (subject_id) REFERENCES public.tab_subject(id);


--
-- TOC entry 3421 (class 2606 OID 36782)
-- Name: tab_professor_groups fk60byudwyqjojjbpfrq0gxt7lh; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_professor_groups
    ADD CONSTRAINT fk60byudwyqjojjbpfrq0gxt7lh FOREIGN KEY (groups_id) REFERENCES public.tab_group(id);


--
-- TOC entry 3422 (class 2606 OID 36787)
-- Name: tab_professor_groups fk63puxy3mbtqx6f5o580awqpal; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_professor_groups
    ADD CONSTRAINT fk63puxy3mbtqx6f5o580awqpal FOREIGN KEY (professor_affiliation_id) REFERENCES public.tab_professor(affiliation_id);


--
-- TOC entry 3408 (class 2606 OID 36717)
-- Name: tab_classroom fk8aafk0xmbyu17bgg5x0h609o; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_classroom
    ADD CONSTRAINT fk8aafk0xmbyu17bgg5x0h609o FOREIGN KEY (id) REFERENCES public.tab_internal_room(id);


--
-- TOC entry 3420 (class 2606 OID 36777)
-- Name: tab_professor fk9jynjy6klyoaka3llgvwulsgm; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_professor
    ADD CONSTRAINT fk9jynjy6klyoaka3llgvwulsgm FOREIGN KEY (affiliation_id) REFERENCES public.tab_public_servant(affiliation_id);


--
-- TOC entry 3412 (class 2606 OID 36737)
-- Name: tab_group fkdqp8ngpf9qd3js484ihqroonu; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_group
    ADD CONSTRAINT fkdqp8ngpf9qd3js484ihqroonu FOREIGN KEY (subject_id) REFERENCES public.tab_subject(id);


--
-- TOC entry 3432 (class 2606 OID 36832)
-- Name: tab_subject_courses fke9291aaoguocsmhtb7tx0y1v0; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_subject_courses
    ADD CONSTRAINT fke9291aaoguocsmhtb7tx0y1v0 FOREIGN KEY (courses_id) REFERENCES public.tab_course(id);


--
-- TOC entry 3417 (class 2606 OID 36762)
-- Name: tab_internal_room fkehpfkbxkw0lbrk6rv4ax40nn; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_internal_room
    ADD CONSTRAINT fkehpfkbxkw0lbrk6rv4ax40nn FOREIGN KEY (building_id) REFERENCES public.tab_building(id);


--
-- TOC entry 3419 (class 2606 OID 36767)
-- Name: tab_lesson_reservation fkei635p6q95hm1siedyg08t6ui; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_lesson_reservation
    ADD CONSTRAINT fkei635p6q95hm1siedyg08t6ui FOREIGN KEY (classroom_id) REFERENCES public.tab_classroom(id);


--
-- TOC entry 3407 (class 2606 OID 36712)
-- Name: tab_affiliation fkgu6awqwjmr1itpkb4p73q4li3; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_affiliation
    ADD CONSTRAINT fkgu6awqwjmr1itpkb4p73q4li3 FOREIGN KEY (user_id) REFERENCES public.tab_user(id);


--
-- TOC entry 3413 (class 2606 OID 36747)
-- Name: tab_group_has_professor fkhfce4yubpknsdt3gw2dkw3671; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_group_has_professor
    ADD CONSTRAINT fkhfce4yubpknsdt3gw2dkw3671 FOREIGN KEY (group_id) REFERENCES public.tab_group(id);


--
-- TOC entry 3414 (class 2606 OID 36742)
-- Name: tab_group_has_professor fkibavjfsqktjdds3lngegneajh; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_group_has_professor
    ADD CONSTRAINT fkibavjfsqktjdds3lngegneajh FOREIGN KEY (professors_affiliation_id) REFERENCES public.tab_professor(affiliation_id);


--
-- TOC entry 3415 (class 2606 OID 36752)
-- Name: tab_group_has_student fkjbkfa6067c9355f7x62ddx6jl; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_group_has_student
    ADD CONSTRAINT fkjbkfa6067c9355f7x62ddx6jl FOREIGN KEY (students_affiliation_id) REFERENCES public.tab_student(affiliation_id);


--
-- TOC entry 3409 (class 2606 OID 36722)
-- Name: tab_computer_laboratory fkk20ewkmjhbvc1t2jul612i20n; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_computer_laboratory
    ADD CONSTRAINT fkk20ewkmjhbvc1t2jul612i20n FOREIGN KEY (id) REFERENCES public.tab_internal_room(id);


--
-- TOC entry 3410 (class 2606 OID 36727)
-- Name: tab_course_has_subject fkknr885u448h7goh7ho96qd24; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_course_has_subject
    ADD CONSTRAINT fkknr885u448h7goh7ho96qd24 FOREIGN KEY (subjects_id) REFERENCES public.tab_subject(id);


--
-- TOC entry 3427 (class 2606 OID 36817)
-- Name: tab_student fkkyvbtqfdu35t4paok1wpmh6xe; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_student
    ADD CONSTRAINT fkkyvbtqfdu35t4paok1wpmh6xe FOREIGN KEY (affiliation_id) REFERENCES public.tab_affiliation(id);


--
-- TOC entry 3426 (class 2606 OID 36807)
-- Name: tab_public_servant_has_role fkl226xgouagx2so99rg6cyxjpr; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_public_servant_has_role
    ADD CONSTRAINT fkl226xgouagx2so99rg6cyxjpr FOREIGN KEY (public_servant_id) REFERENCES public.tab_public_servant(affiliation_id);


--
-- TOC entry 3411 (class 2606 OID 36732)
-- Name: tab_course_has_subject fkm39u6ad9raw3qojaskwv64xx7; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_course_has_subject
    ADD CONSTRAINT fkm39u6ad9raw3qojaskwv64xx7 FOREIGN KEY (course_id) REFERENCES public.tab_course(id);


--
-- TOC entry 3423 (class 2606 OID 36792)
-- Name: tab_public_servant fknsnrjg8yy349vyho77gkdjydb; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_public_servant
    ADD CONSTRAINT fknsnrjg8yy349vyho77gkdjydb FOREIGN KEY (department_id) REFERENCES public.tab_department(id);


--
-- TOC entry 3428 (class 2606 OID 36812)
-- Name: tab_student fkofyng9cuud38t4bewdlhqoc37; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_student
    ADD CONSTRAINT fkofyng9cuud38t4bewdlhqoc37 FOREIGN KEY (course_id) REFERENCES public.tab_course(id);


--
-- TOC entry 3406 (class 2606 OID 36707)
-- Name: tab_administrative_public_servant fkr1rjjsu6olnv3x8epbkjaptd3; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_administrative_public_servant
    ADD CONSTRAINT fkr1rjjsu6olnv3x8epbkjaptd3 FOREIGN KEY (affiliation_id) REFERENCES public.tab_public_servant(affiliation_id);


--
-- TOC entry 3424 (class 2606 OID 36797)
-- Name: tab_public_servant fks9lkowcy31hr5qr32h3n6dgus; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_public_servant
    ADD CONSTRAINT fks9lkowcy31hr5qr32h3n6dgus FOREIGN KEY (affiliation_id) REFERENCES public.tab_affiliation(id);


--
-- TOC entry 3416 (class 2606 OID 36757)
-- Name: tab_group_has_student fksk2391mq2qu89jewybwcktda6; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_group_has_student
    ADD CONSTRAINT fksk2391mq2qu89jewybwcktda6 FOREIGN KEY (group_id) REFERENCES public.tab_group(id);


--
-- TOC entry 3434 (class 2606 OID 36847)
-- Name: tab_user_has_role fkssrounfohxjwa2mcsko8r339n; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tab_user_has_role
    ADD CONSTRAINT fkssrounfohxjwa2mcsko8r339n FOREIGN KEY (user_id) REFERENCES public.tab_user(id);


-- Completed on 2024-12-20 01:54:06 UTC

--
-- PostgreSQL database dump complete
--

